name: ExplosionPlugin
version: '${project.version}'
main: me.axl.explosionplugin.explosionplugin.ExplosionPlugin
api-version: 1.18
authors: [ Axl ]
description: A plugin that spawns TNTs around a selected player.
commands:
  givetnt:
    description: Gives 20 TNT to a selected player. If no player is specified, TNTs are given to the command-issuer.
    usage: /<command> [player]
  explode:
    description: Spawns primed TNTs around a selected player. If no player is specified, TNTs are spawned around the command issuer.
    usage: /<command> [player]
